### PR TITLE
Switch the console.error with debuglog

### PR DESCRIPTION
**Pull request by phated**
This reduces noise on "failure" tests.  It also lets users decide if they want the warnings by opting in by setting `NODE_DEBUG=thrift-parser` in their environment.

### CODE REVIEW

**Comment by YanagiEiichi** [comment]
Avoid requiring more nodejs feature, that will cause browser side developer trouble.

I think let the error tip message be a property of ThriftFileParsingError is a better solution.

**Comment by phated** [comment]
All bundlers will resolve `utils` properly and make available `process.env`.  I think a proper logging solution like this will be helpful in the future also.

**Comment by phated** [comment]
@YanagiEiichi what if I inlined similar logic to https://github.com/sam-github/node-debuglog/blob/master/debuglog.js that works in browsers or node?

**Comment by YanagiEiichi** [comment]
A parser should be idempotent, shouldn't log anything to system io. Like the `JSON.parse`, that just throw an error contains detail message. You can catch the parser error an log it in your project.

**Comment by phated** [comment]
So the logging that's there now should be completely removed?

**Comment by YanagiEiichi** [comment]
Yes, let the error tip message be a property of ThriftFileParsingError.

**Comment by phated** [comment]
Closing in favor of #13

**Pull request closed without merging**
