### PR TITLE
Add prepublish hook which compiles code into ES5

### PR DESCRIPTION
**Pull request by tonyseek**
Or the UglifyJS plugin of webpack 2.x will crash.

### CODE REVIEW

**Comment by phated** [comment]
👎  Why is this in your bundle tree?

**Comment by tonyseek** [comment]
Sorry, I guess I didn't understand. Do you mean some files?

**Comment by phated** [comment]
Why is this being bundled (assuming for the client-side)?  Are you parsing thrift files in the browser?  Also, uglifyjs should be parsing es2015 at this point; maybe webpack didn't upgrade?

**Comment by tonyseek** [comment]
Yes, we are parsing thrift files in the browser side, for a service management console.

It seems the ES2015 support of uglifyjs is still a open issue (https://github.com/webpack/webpack/issues/2545 & https://github.com/mishoo/UglifyJS2/issues/448)

**Comment by phated** [comment]
Another option is to explicitly add this module to your ES2015 compilation plugin.  If you are using the babel plugin with webpack, you can loosen your ignore regexp.

**Comment by tonyseek** [comment]
It works of course but looks like a workaround.

I don't know whether @YanagiEiichi plan to build this library as an isomorphic library. If he does, backward compatibility may not be bad.

**Comment by phated** [comment]
Even if he does, I think the library is better suited for TypeScript (typings already included in devDeps).

**Comment by YanagiEiichi** [comment]
@tonyseek  Isomorphism is feasible. But now some nodejs features such as `Buffer` and `path` has been used in this library.

**Comment by tonyseek** [comment]
@YanagiEiichi For `Buffer` and `path`, both [feross/buffer](https://github.com/feross/buffer) and [substack/path-browserify](https://github.com/substack/path-browserify) work in browser side. Should I add them to the README file or the `package.json` as optional dependency?

**Pull request closed without merging**
